### ISSUE TITLE
One Click - Phials Notes -

### ISSUE THREAD

**Issue by Ivoe** [Ganom/ExternalPlugins#101]
Phials - id 15821

Noted Planks
   Planks - id 961
   Oak - id 8779
   Teak - 8781
   Mahogany - id 8783

Noted Bones
   Bones - id 527
   Big Bones - id  533
   Dragon Bones - id 537
   
Noted Soft Clay - id 1762

use item on phials

**Comment by xKylee** [comment]
@Ivoe can you get a list of ID’s of every notes plank, and every noted bone? :)

**Comment by Ivoe** [comment]
@xKylee Most used ones are the ids. in noted form.
i don't know all the bones that work for the guilded alter 
or what else someone needs to do Construction.

**Comment by Rubueno** [comment]
@xKylee I came across this wanted feature myself too. Here's a list of the requested IDs:

All noted bones IDs:
```
527
529
531
533
535
537
2531
2860
3124
3126
3184
4813
4831
4833
4835
6730
6816
11944
22125
22781
22784
22787
25200
```

All noted planks IDs:
```
961
8779
8781
8783
```

**Comment by Rubueno** [comment]
Phials ID: `1614`

**Comment by Rubueno** [comment]
IDs found at https://www.osrsbox.com/tools/item-search/
