### ISSUE TITLE
Please remove Trident from One Click Cast

### ISSUE THREAD

**Issue by rokaHakor** [Ganom/ExternalPlugins#127]
One Click Cast conflicts with the charged auto attack of trident and requires you to right click to use the auto attack. 
No one uses Tridents for PvP anyway. Removing Trident will make it easier to do content where you use Trident and Ancient Magicks like ToB.

Found on like 283 of LeftClickCast.java
if (name.contains("staff") || name.contains("wand") || name.contains("sceptre") || name.contains("trident"))

**Comment by RAT-STOMPER** [comment]
People DO pk with trident. especially on DMM. Just turn off left click cast while you do zulrah
