### ISSUE TITLE
Plugin Update

### ISSUE THREAD

**Issue by Kisstehflo** [Ganom/ExternalPlugins#132]
Hey,

The new OpenOSRS update broke the way plugins were setup. This means the plugins no longer work on the current version of OpenOSRS.

Thanks,

**Comment by michaejmoore** [comment]
Any chance of them working again?

**Comment by Kisstehflo** [comment]
> Any chance of them working again?

Hey, it looks like Ganom has updated the plugins. You just add the repository again and install the plugin to your client. It should be all good to go.
