### ISSUE TITLE
Item Dropper and Shift Drop

### ISSUE THREAD

**Issue by ThirstyCodes** [Ganom/ExternalPlugins#135]
When using the item dropper you MUST hold shift in order for it to drop the items. Is this intentional? I do not see it in the documentation. 

For example if I set it to drop items by pressing the "\" key it will simply only highlight the items and try to use them on the next item in the row. However if I am holding shift during the action, it drops the items.

**Comment by BigolDukes** [comment]
Same issue here

**Comment by JYount14** [comment]
Check if you have "Request Focus" set to "Force" in "Runelight" settings. This seems to break it for me and I have to hold shift until I restart the client.

**Comment by BigolDukes** [comment]
> Check if you have "Request Focus" set to "Force" in "Runelight" settings. This seems to break it for me and I have to hold shift until I restart the client.

Nope, doesn't change anything :/

**Comment by ajbinky** [comment]
Any update on this?
