### ISSUE TITLE
Add "Return Mouse to Previous Position" Feature

### ISSUE THREAD

**Issue by bigmemes420** [Ganom/ExternalPlugins#17]
Basically puts your mouse back before you used any of the features.
IE: You have your mouse over the woodcutting skill and have it swap pray melee to pray mage, it would move your mouse back to the woodcutting skill.

**Comment by KingLycosa** [comment]
The mouse events setting does this.

**Comment by tomcylke** [comment]
Making the flexo setting return the mouse to the original position kinda defeats the point of using flexo. It's supposed to be random and making the mouse start/end at exactly the same place is more detectable. Mouse events are good.

**Comment by Ganom** [comment]
Tom summed it up well.
