### ISSUE TITLE
Custom Swapper & Left Click Cast NOT WORKING 

### ISSUE THREAD

**Issue by danny3o5** [Ganom/ExternalPlugins#188]
After the latest Inventory Update Custom Swapper & Left Click Cast are both dead plugins. Neither one has any working features. Please update, Thank You in Advance!

**Comment by chewers13** [comment]
So are they working on this or no? It's still not working

**Comment by xBusse** [comment]
> So are they working on this or no? It's still not working

Yes, they are working on it.  They have dozens of plugins that all needed to be updated because of the "updates" from the other day.  Many have been fixed, many more are being fixed as we speak.

**Comment by Failed4life** [comment]
The Free plugins are our last priority, they will be updated once the Platinum and Bronze plugins are fully back up and running

**Comment by slapdaddy500** [comment]
thanks for update, was unsure about the left click cast, any idea of when we could expect to see it updated? thx in advance <3

**Comment by Ganom** [comment]
To give a bit of info, the reason why they haven't been updated is that the entire plugin needs to be rewritten for the new IF3 inventory, which is not an easy undertaking.

**Comment by slapdaddy500** [comment]
> To give a bit of info, the reason why they haven't been updated is that the entire plugin needs to be rewritten for the new IF3 inventory, which is not an easy undertaking.

Great! Was unsure if you knew about the problem, but I can now rest easy knowing daddy ganom is on the case

**Comment by cow1337killer3** [comment]
> The Free plugins are our last priority, they will be updated once the Platinum and Bronze plugins are fully back up and running

How do we buy the Platinum plugins? The Discord invite is broken

**Comment by slapdaddy500** [comment]
left click clast is now working
