### ISSUE TITLE
OneClick: Runes

### ISSUE THREAD

**Issue by petcat5** [Ganom/ExternalPlugins#195]
With the new update you can no longer 1 tick empty pouches and craft. The menu swap is only there when you have essence in your inventory so you have to wait a tick after emptying pouches.

**Comment by Ganom** [comment]
> With the new update you can no longer 1 tick empty pouches and craft. The menu swap is only there when you have essence in your inventory so you have to wait a tick after emptying pouches.

That's a good point, I didn't think about that tbh.

**Comment by petcat5** [comment]
Works great. Thanks for the quick fix.
