### ISSUE TITLE
Auto Pray Flick: Hard Crashes on Mac M1

### ISSUE THREAD

**Issue by magicman567** [Ganom/ExternalPlugins#196]
When I try pressing the Auto Pray Flick plugin's flick hotkey on my Mac M1, my client hard crashes. This plugin does not cause my client to crash when I use my Windows computer.

**Comment by Ganom** [comment]
> When I try pressing the Auto Pray Flick plugin's flick hotkey on my Mac M1, my client hard crashes. This plugin does not cause my client to crash when I use my Windows computer.

Sounds like a permissions, or jvm issue, neither of which can be fixed by me.
