### ISSUE TITLE
Custom swapper

### ISSUE THREAD

**Issue by castielxxxx** [Ganom/ExternalPlugins#198]
Hi was wondering how do you use custom swappper keeps coming up with a error wanna use it for pvp

**Comment by Failed4life** [comment]
Custom Swapper syntax:
• ID:Equip equips the item (left clicks on it)
• ID:Remove removes equipped item
• ID:Clean clicks all items with this ID in your inventory
• SpellName:Cast clicks on spell
• PrayerName:Prayer activates the prayer (or disables it if Active Prayer Check is disabled)
• Spec:Enable activates special attack

Example:
4091:Equip
4093:Equip
4675:Equip
Augury:Prayer
Ice barrage:Cast

**Comment by castielxxxx** [comment]
Huh what seems so complex is there a video
