### ISSUE TITLE
item dropper stops dropping starts using

### ISSUE THREAD

**Issue by thhdragon** [Ganom/ExternalPlugins#66]
after a bit of use the item dropper plugin starts to click use on the items instead of drop.

**Comment by Ganom** [comment]
Fixed

**Comment by akozakowski** [comment]
Seems that this bug has reoccurred. Trying to drop Raw salmon and Raw Trout (335, 331). Around the 24th item spot is when it seems to start using the fish on each other instead of dropping.
Min Delay: 170
Max Delay: 300

**Comment by ImDunnHere** [comment]
This is happening to me except none of the items are dropping. Instead , the plugin is 'using' all of the selected items and not dropping them. How do I fix this?
