### ISSUE TITLE
[CustomSwapper] Unable to use the same key-bind twice in a row

### ISSUE THREAD

**Issue by Alechilles** [Ganom/ExternalPlugins#71]
In the latest CustomSwapper release pressing the same key-bind twice in a row will not work. The first press will work, then any consecutive presses will not. If another CustomSwapper key-bind is pressed the first bind can be pressed again successfully.

Steps to Reproduce:

1. Set Set 1 to "Protect from Melee:Prayer"
2. Set key-bind 1 to Numpad-1
3. Press key-bind 1
    - Protect from Melee will be toggled
4. Press key-bind 1
    - Protect from Melee will *not* be toggled
5. Press another CustomSwapper key-bind
    - This will work properly
6. Press key-bind 1 again
    - Protect from Melee will be properly toggled again

**Comment by Ganom** [comment]
Fixed by: https://github.com/Ganom/ExternalPlugins/commit/c7cfd419a236adcd03ad82a5fa507173fa55d11f
