### ISSUE TITLE
Item dropper

### ISSUE THREAD

**Issue by kul782** [Ganom/ExternalPlugins#88]
The item dropper plugin is glitching and doesn't wanna drop the 5-8 last items, it just left-clicks on them not proceeding to drop them

**Comment by Dankseed** [comment]
I can't seem to get the item dropper to work at all... any ideas? I put in the correct item IDs, but maybe did not format properly.

**Comment by CodyBontecou** [comment]
> I can't seem to get the item dropper to work at all... any ideas? I put in the correct item IDs, but maybe did not format properly.

@Dankseed You probably just need to reset the client. This is my current config and it's working well enough for barbarian fishing:
<img width="233" alt="Screen Shot 2020-07-05 at 11 06 23" src="https://user-images.githubusercontent.com/20440899/86536761-aed57380-beaf-11ea-956f-338384d056ad.png">

I am running into the same issue as posted here though. Last 8 items never get dropped unless I hit my keybind a second time.

**Comment by sirmaxxo** [comment]
Still having the same issue with the last few items not dropping
