### ISSUE TITLE
discord links broken

### ISSUE THREAD

**Issue by code-altered** [Ganom/ExternalPlugins#89]

**Comment by Crystalknoct** [comment]
Pretty sure its intentional of ganoms choosing.

**Comment by herewegothen** [comment]
Do you think he'll change this anytime soon?  I would like to use his platinum stuff :)

**Comment by GantaRS** [comment]
> Do you think he'll change this anytime soon? I would like to use his platinum stuff :)


You can get invited to the discord by buying platinum on patreon. The bot will then get you invited. If you want to buy platinum with GP, contact "Failed4life#3370" and he will get you sorted.
